package wikisimple

import grails.core.GrailsApplication
import grails.util.Environment

class BootStrap {

    GrailsApplication grailsApplication

    def init = { servletContext ->
        Environment.executeForEnvironment(Environment.DEVELOPMENT){
            Content lorem = new Content(content:"Vita est illis semper in fuga uxoresque mercenariae conductae ad tempus ex pacto atque, ut sit species matrimonii, dotis nomine futura coniunx hastam et tabernaculum offert marito, post statum diem si id elegerit discessura, et incredibile est quo ardore apud eos in venerem uterque solvitur sexus.").save()
            Content bacon = new Content(content: "Spicy jalapeno bacon ipsum dolor amet ham hock sirloin ground round brisket. Chuck tri-tip jowl, beef andouille ball tip kielbasa chicken prosciutto shankle ham capicola turducken. Picanha cupim pork loin alcatra ribeye buffalo shankle venison shank jowl brisket. Kevin salami drumstick rump meatball leberkas sausage flank beef venison pork loin pancetta ham hock. Short loin spare ribs picanha, pork loin pig tail salami pastrami beef ribs ribeye chicken. Filet mignon pork ribeye chicken, doner corned beef chuck flank andouille swine.").save()
            Content cat = new Content(content: "Stare at wall turn and meow stare at wall some more meow again continue staring . Meow to be let out jump off balcony, onto stranger's head but purr for no reason but scratch me there, elevator butt, annoy kitten brother with poking. Purrrrrr drink water out of the faucet yet cat dog hate mouse eat string barf pillow no baths hate everything kitty scratches couch bad kitty kitty power pounce on unsuspecting person. Intrigued by the shower white cat sleeps on a black shirt or make muffins, and demand to have some of whatever the human is cooking, then sniff the offering and walk away or hunt by meowing loudly at 5am next to human slave food dispenser but curl up and sleep on the freshly laundered towels. Sit and stare poop on grasses show belly lick the curtain just to be annoying so run around the house at 4 in the morning yet milk the cow. Curl into a furry donut annoy the old grumpy cat, start a fight and then retreat to wash when i lose yet play time, so burrow under covers cat mojo , meowzer. Sniff catnip and act crazy cat slap dog in face. ").save()
            Content ww2 = new Content(content: "La Seconde Guerre mondiale ou Deuxième Guerre mondiale4 est un conflit armé à l'échelle planétaire qui dura du 1er septembre 1939 au 2 septembre 1945. Ce conflit opposa schématiquement deux camps : les Alliés et l’Axe.\n" +
                    "\n" +
                    "Provoquée par le règlement insatisfaisant de la Première Guerre mondiale et par les ambitions expansionnistes et hégémoniques des trois principales nations de l’Axe (Allemagne nazie, Italie fasciste et Empire du Japon), elle fut favorisée par la convergence, à partir du 3 septembre 1939, d’un ensemble de conflits régionaux respectivement amorcés le 18 juillet 1936 en Espagne (la guerre d'Espagne), le 7 juillet 1937 en Chine (la guerre sino-japonaise), et le 1er septembre 1939 en Pologne (l'agression allemande contre la Pologne). C'est ce dernier évènement qui provoqua l'entrée en guerre de la France et du Royaume-Uni, et de leurs empires coloniaux respectifs, dès le 3 septembre 1939.\n" +
                    "\n" +
                    "Tout d'abord associée à l'Allemagne dans le partage de l'Europe, l'URSS rejoint le camp allié à la suite de l'invasion allemande le 22 juin 1941. Quant aux États-Unis, ils abandonnent leur neutralité après l'attaque de Pearl Harbor le 7 décembre 1941. Dès lors, le conflit devient vraiment mondial, impliquant toutes les grandes puissances, et la majorité des nations du monde sur la quasi-totalité des continents.\n" +
                    "\n" +
                    "La Seconde Guerre mondiale prend fin sur le théâtre d'opérations européen le 8 mai 1945 par la capitulation sans condition du Troisième Reich, puis s’achève définitivement sur le théâtre d'opérations Asie-Pacifique le 2 septembre 1945 par la capitulation également sans condition de l'Empire du Japon, dernière nation de l’Axe à connaître une défaite totale.\n" +
                    "\n" +
                    "La Seconde Guerre mondiale constitue le conflit armé le plus vaste que l’humanité ait connu, mobilisant plus de 100 millions de combattants de 61 nations, déployant les hostilités sur quelque 22 millions de km25, et tuant environ 62 millions de personnes, dont une majorité de civils. N’opposant pas seulement des nations, la Seconde Guerre mondiale fut aussi la plus grande guerre idéologique de l’Histoire, ce qui explique que les forces de collaboration en Europe et en Asie occupées aient pu être solidaires de pays envahisseurs ou ennemis, ou qu’une résistance ait pu exister jusqu’en plein cœur de l’Allemagne nazie en guerre. Guerre totale, elle gomma presque totalement la séparation entre espaces civils et militaires et vit, dans les deux camps, la mobilisation poussée non seulement des ressources matérielles – économiques et scientifiques – mais aussi morales et politiques, dans un engagement des sociétés tout entières.\n" +
                    "\n" +
                    "La somme des dégâts matériels n’a jamais pu être chiffrée avec certitude. Les pertes en vies humaines et les traumatismes collectifs et individuels ne furent pas moins considérables, la violence ayant pris des proportions inédites. Le conflit donna lieu à de multiples crimes de guerre, qui ne furent l'apanage d'aucun camp, crimes s'insérant dans une violence militaire et policière d'une intensité et d'une profondeur inégalées, cette violence notamment contre les civils étant parfois un élément de la stratégie militaire. On assista ainsi à l'émergence à une échelle inconnue jusqu'alors de crimes de masse particulièrement atroces et pour certains sans précédents, tout particulièrement à l'instigation de l'Allemagne nazie et du Japon impérial. Parmi ces crimes figure la déportation en camps de concentration, camps de travail et camps d'extermination, comportant des chambres à gaz à des fins d’extermination de populations entières (Juifs, Slaves, Tziganes) ou de catégories particulières d’individus (homosexuels, handicapés, etc.) commandée par le régime nazi. L'ampleur des crimes suscita la définition d'une incrimination nouvelle : le crime contre l'humanité, appliquée notamment au génocide des juifs d'Europe. Le régime Shōwa ne fut nullement en reste en Asie avec, à son actif, dix millions de civils chinois enrôlés de force par la Kōa-in au Mandchoukouo, environ 200 000 « femmes de réconfort » enrôlées en Corée et dans tout l’Extrême-Orient, ainsi que l’annihilation systématique de populations civiles, principalement en Chine et notamment lors du massacre de Nankin.").save()

            Content cup = new Content(content: "Cupcake ipsum dolor sit amet chocolate cake chocolate halvah. Dessert muffin tootsie roll icing fruitcake gummies liquorice. Macaroon jujubes fruitcake icing cake. Liquorice icing gummies fruitcake ice cream lollipop muffin halvah. Sweet roll oat cake cotton candy wafer topping carrot cake bear claw gummi bears. Sweet roll tart chocolate oat cake. Fruitcake chocolate bar halvah. Dragée caramels sugar plum caramels danish. Ice cream halvah icing marshmallow jelly-o tootsie roll candy canes sweet roll. Cupcake cookie tart apple pie jelly beans. Croissant wafer sweet. Liquorice soufflé cotton candy halvah jujubes jujubes tart. Cupcake dessert icing lemon drops tootsie roll halvah chocolate bar. Gummi bears toffee jelly-o.\n" +
                    "Cupcake chocolate cake gummies. Jelly-o bonbon cookie sweet gummi bears chocolate cake. Powder fruitcake jujubes sugar plum. Cake gummies jujubes donut. Cupcake lemon drops marshmallow gummi bears. Cheesecake dessert fruitcake jujubes. Sweet tart jelly beans. Jelly-o sweet macaroon gummi bears macaroon cupcake toffee. Topping wafer cake biscuit pastry gingerbread. Oat cake icing marzipan cake. Jelly-o donut marshmallow chocolate bar. Tiramisu wafer dessert ice cream brownie. Cupcake halvah tiramisu ice cream. Bear claw pastry lollipop bear claw cake apple pie dragée lemon drops.\n" +
                    "Candy chocolate cake sugar plum chocolate. Pudding brownie cupcake cake icing bonbon topping marshmallow macaroon. Muffin gummies bear claw sweet pie biscuit danish. Sweet roll tart icing tiramisu lollipop. Lollipop chupa chups halvah chocolate carrot cake. Ice cream sugar plum gummi bears biscuit oat cake croissant. Liquorice halvah icing oat cake liquorice sesame snaps halvah. Dragée oat cake chocolate cake cake. Muffin sugar plum jelly-o cheesecake macaroon. Fruitcake caramels apple pie. Cotton candy dessert pudding danish. Toffee cotton candy muffin chocolate dessert soufflé pie muffin.\n" +
                    "Chocolate lollipop tart dragée chupa chups jujubes. Pastry halvah sugar plum biscuit danish bonbon cheesecake caramels. Gummies oat cake soufflé topping. Icing ice cream candy sesame snaps pastry cookie cotton candy. Gummies jelly-o candy canes bonbon gingerbread. Carrot cake chocolate cheesecake pie danish ice cream gingerbread sweet. Pastry liquorice sweet chocolate sweet cheesecake. Apple pie macaroon donut cookie pudding oat cake. Biscuit muffin cotton candy dessert. Pudding toffee jujubes cotton candy marzipan. Carrot cake donut donut. Tart danish danish soufflé. Toffee cookie dessert cotton candy powder bonbon cheesecake sesame snaps.\n" +
                    "Tiramisu tiramisu toffee. Soufflé tiramisu chocolate bar. Jelly gingerbread tart marshmallow sweet roll. Pudding sesame snaps candy fruitcake. Gummies sugar plum wafer carrot cake lemon drops fruitcake jelly beans chocolate bar. Pie dessert liquorice dragée chocolate pudding topping caramels jelly-o. Gingerbread jelly-o icing cookie lollipop marshmallow. Macaroon macaroon chocolate bar candy canes. Candy chupa chups lollipop ice cream. Brownie tootsie roll lollipop bonbon apple pie gingerbread. Brownie sesame snaps candy candy canes chupa chups gummies. Marzipan dessert sweet roll wafer macaroon. Candy cake caramels macaroon cupcake.").save()

            Content bob = new Content(content: "I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's build an almighty mountain. You are only limited by your imagination. That's what painting is all about. It should make you feel good when you paint. Of course he's a happy little stone, cause we don't have any other kind. Let your heart take you to wherever you want to be.\n" +
                    "\n" +
                    "In nature, dead trees are just as normal as live trees. Anytime you learn something your time and energy are not wasted. That's a crooked tree. We'll send him to Washington. Nothing wrong with washing your brush.\n" +
                    "\n" +
                    "We'll have a super time. Now let's put some happy little clouds in here. You want your tree to have some character. Make it special. We'll take a little bit of Van Dyke Brown. There are no mistakes. You can fix anything that happens. You can create anything that makes you happy.\n" +
                    "\n" +
                    "And just raise cain. This is gonna be a happy little seascape. Let's have a little bit of fun today.\n" +
                    "\n" +
                    "Every highlight needs it's own personal shadow. Volunteering your time; it pays you and your whole community fantastic dividends. Let's make some happy little clouds in our world.\n" +
                    "").save()

            Content hairy = new Content(content: "Consectetur circus strongman basil fawlty Daniel plainview Refined gentlemen, basil fawlty d’artagnan kaiser bill consectetur waiter sterling tricky sneezes Refined gentlemen consectetur Daniel plainview circus strongman, kaiser bill d’artagnan tricky sneezes circus strongman chevron Daniel plainview Refined gentlemen consectetur professor plum waiter sterling consectetur handsome basil fawlty.\n" +
                    "\n" +
                    "Villain toothbrush French café patron saddam hussein Droopy. Decathlon champion lando calrissian off-piste ron jeremy bruce forsyth vincent price, will you do the fandango frontiersman off-piste decathlon champion waiter lando calrissian mustachioed fox hunting magnum pi bruce forsyth sportacus vincent price ron jeremy, waiter will you do the fandango bruce forsyth off-piste sportacus ron jeremy felis fox hunting decathlon champion lando calrissian hair trimmer mustachioed bruce forsyth Nostrilis tickler sweat irrigator, frontiersman decathlon champion vincent price magnum pi ian botham albert einstein?\n" +
                    "\n" +
                    "Middle eastern despot Semi beard dickie davies grooming challenge you to a duel kris kristofferson., marquess of queensbury colonel mustard kris kristofferson. dickie davies middle eastern despot karl marx challenge you to a duel Semi beard movember handsome chevron hello, we’re cockneys jolly good show grooming?\n" +
                    "\n" +
                    "Id furry facial friend admiral dickie davies saddam hussein vincent price, bad guy furry facial friend brad pitt vincent price French café patron got milk id saddam hussein worn with distinction villain admiral dickie davies gunslinger. Godlike furry facial friend gentleman Sergeant major worn with distinction Milkshake issues, furry facial friend testosterone trophy doctor strange worn with distinction face broom godlike Milkshake issues gentleman musketeer Sergeant major, worn with distinction face broom gentleman great dictator Sergeant major musketeer d’artagnan testosterone trophy jimi hendrix brush doctor strange furry facial friend Milkshake issues rock n roll star godlike.\n" +
                    "\n" +
                    "Groucho marx hairy kid at school theodore roosevelt cigars clone zone shopper magnum pi, lipwig groucho marx magnum pi theodore roosevelt cigars great dictator clone zone shopper burt reynolds hairy kid at school.").save()

            Content hodor = new Content(content: "Hodor! Hodor hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor. Hodor. Hodor! Hodor hodor, hodor... Hodor hodor hodor... Hodor hodor hodor... Hodor hodor hodor. Hodor. Hodor hodor - hodor - hodor hodor. Hodor. Hodor hodor hodor... Hodor hodor hodor, hodor. Hodor hodor hodor. Hodor. Hodor, hodor. Hodor. Hodor, hodor... Hodor hodor hodor hodor! Hodor hodor - HODOR hodor, hodor hodor HODOR hodor, hodor hodor?\n" +
                    "\n" +
                    "Hodor. Hodor hodor hodor hodor, hodor. Hodor hodor hodor hodor. Hodor. Hodor. Hodor HODOR hodor, hodor hodor hodor - hodor - hodor, hodor, hodor hodor. Hodor! Hodor hodor, hodor, hodor. Hodor hodor; hodor hodor. Hodor. Hodor! Hodor hodor, hodor hodor hodor. Hodor. Hodor. Hodor hodor, hodor. Hodor HODOR hodor, hodor hodor... Hodor hodor hodor?\n" +
                    "\n" +
                    "Hodor HODOR hodor, hodor hodor? Hodor, hodor... Hodor hodor hodor; hodor hodor hodor hodor! Hodor hodor hodor hodor? Hodor! Hodor hodor, hodor hodor - hodor hodor hodor? Hodor, hodor... Hodor hodor hodor... Hodor hodor hodor. Hodor hodor... Hodor hodor hodor. Hodor.").save()

            Content pirate = new Content(content: "Aye cutlass flogging Nelsons folly booty jack gun brigantine Letter of Marque warp. Fire ship matey keel code of conduct cutlass Gold Road hornswaggle lass keelhaul scurvy. Jib boatswain topsail no prey, no pay avast crow's nest coxswain American Main wench rope's end.\n" +
                    "Handsomely Plate Fleet Sea Legs Jack Ketch cog draft heave down come about walk the plank boom. Maroon barque scallywag marooned avast swing the lead loot shrouds squiffy gabion. Avast Letter of Marque sheet run a rig Jack Tar furl reef sails bounty mutiny Chain Shot.\n" +
                    "Yellow Jack heave down topsail jib starboard mutiny Chain Shot prow scuttle Blimey. Jury mast long boat parley log loaded to the gunwalls grapple black spot hands list pirate. Grog snow loaded to the gunwalls stern trysail clap of thunder careen Spanish Main walk the plank chantey.").save()

            Content pommy = new Content(content: "Pommy ipsum ponce cockney The Doctor, chippy leisurely taking the mick. Gravy cheese and chips nonsense it's the bees knees stupendous numbskull hedgehog accordingly, indeed marmite cobbles biscuits eton mess. Union Jack sling one's hook munta pikey, tosser odds and sods. Snotty nosed brat conked him one on the nose owt scally for sooth 221B Baker Street through the dales, pulled out the eating irons fried toast that's ace brown sauce could murder a pint, in a pickle daft cow nutter ridiculous marmite. Fork out skive Bob's your uncle bull dog ponce bull dog driving a mini posh nosh, Sherlock goggledegook Sonic Screwdriver on a stag do and we all like figgy pudding curry sauce could murder a pint not some sort of dosshouse, fake tan wedding tackle balderdash ee bah gum sod's law don't get your knickers in a twist absolute.\n" +
                    "\n" +
                    "On the pull bloody shambles conkers barmy loo bottled it, see a man about a dog naff had a barney with the inlaws. Posh nosh lass sausage roll superb rambunctious I bid you good day football, pompous come hither fake tan quid 10 pence mix a comely wench, got his end away easy peasy bowler hat clotted cream it's nicked. Fork out Kate and Will cotton on pikey guinness pulled a right corker, ponce 221B Baker Street ridicule bits 'n bobs, it's spitting give you a bell Sonic Screwdriver pie-eyed. Fancied a flutter a bit miffed sweets alright duck smeg pants toad in the whole, morris dancers Prince Charles stiff upper lip accordingly.\n" +
                    "\n" +
                    "Macca grab a jumper barmy in the jacksy Bob's your uncle devonshire cream tea, sweet fanny adams spend a penny got a lot of brass got his end away old chap fake tan, clotted cream made a pig's ear of it alright geezer willy. Bent as a nine bob note wibbly-wobbly timey-wimey stuff it's nicked football codswallop have a gander up the duff absobloodylootely and we all like figgy pudding bugger, completely starkers black cab pork scratchings eton mess ey up chuck fried toast Dalek blighty. Flabbergasted up the duff brainbox oopsy-daisies on the pull, chinwag pork scratchings. Through the dales codswallop chuffed fake tan for sooth make a brew, cornish pasty clotted cream 'ar kid.\n" +
                    "\n" +
                    "chuffed have a kip. Cotton on stiff upper lip horses for courses wedding tackle balderdash brown sauce a tad in the jacksy gobsmacked, crumpets Moriarty round our gaff in the jacksy splendid oo ecky thump. Essex girls I bid you good day bent as a nine bob note brown sauce shepherd's pie, squirrel that's ace we'll be 'avin less of that chin up slappers, pork dripping the dog's dinner is she 'avin a laugh. Roast beef driving a mini roast beef, gosh.").save()

            Content cosmos = new Content (content: "Cosmic ocean how far away. Explorations descended from astronomers consciousness cosmic fugue the carbon in our apple pies, Drake Equation vastness is bearable only through love circumnavigated dream of the mind's eye corpus callosum the ash of stellar alchemy. Citizens of distant epochs Hypatia from which we spring. The ash of stellar alchemy vastness is bearable only through love corpus callosum radio telescope the only home we've ever known venture star stuff harvesting star light from which we spring, finite but unbounded astonishment light years? Corpus callosum courage of our questions dispassionate extraterrestrial observer courage of our questions from which we spring?\n" +
                    "Decipherment permanence of the stars quasar! Dispassionate extraterrestrial observer something incredible is waiting to be known. Jean-Francois Champollion, permanence of the stars. Two ghostly white figures in coveralls and helmets are soflty dancing of brilliant syntheses cosmic fugue, corpus callosum, a very small stage in a vast cosmic arena Jean-Francois Champollion extraplanetary Hypatia preserve and cherish that pale blue dot network of wormholes. Quasar encyclopaedia galactica galaxies something incredible is waiting to be known, take root and flourish something incredible is waiting to be known globular star cluster! Tunguska event Drake Equation tesseract, network of wormholes rich in mystery?\n" +
                    "Explorations emerged into consciousness. Birth star stuff harvesting star light, Sea of Tranquility Orion's sword. Hearts of the stars? Billions upon billions? Not a sunrise but a galaxyrise Jean-Francois Champollion take root and flourish laws of physics stirred by starlight Vangelis hydrogen atoms, something incredible is waiting to be known across the centuries? The sky calls to us another world colonies dispassionate extraterrestrial observer. Emerged into consciousness quasar courage of our questions tingling of the spine Cambrian explosion white dwarf quasar colonies descended from astronomers something incredible is waiting to be known Jean-Francois Champollion billions upon billions?\n" +
                    "Cambrian explosion, great turbulent clouds vastness is bearable only through love Cambrian explosion. Inconspicuous motes of rock and gas the ash of stellar alchemy? Hundreds of thousands cosmic ocean science are creatures of the cosmos! Hearts of the stars shores of the cosmic ocean, prime number a mote of dust suspended in a sunbeam Sea of Tranquility prime number? Corpus callosum! As a patch of light. Emerged into consciousness the sky calls to us, how far away. Finite but unbounded. Cosmos descended from astronomers corpus callosum, muse about paroxysm of global death stirred by starlight descended from astronomers, Vangelis! Tesseract are creatures of the cosmos, another world. Rig Veda permanence of the stars extraordinary claims require extraordinary evidence Orion's sword.\n" +
                    "Muse about circumnavigated a mote of dust suspended in a sunbeam! Courage of our questions? Citizens of distant epochs across the centuries the ash of stellar alchemy ship of the imagination. Consciousness a billion trillion, Jean-Francois Champollion. Culture! A mote of dust suspended in a sunbeam permanence of the stars ship of the imagination decipherment the sky calls to us gathered by gravity. With pretty stories for which there's little good evidence. The ash of stellar alchemy, courage of our questions inconspicuous motes of rock and gas. Hypatia!\n" +
                    "As a patch of light hundreds of thousands billions upon billions, hundreds of thousands the sky calls to us. Billions upon billions a mote of dust suspended in a sunbeam, cosmic fugue. The ash of stellar alchemy, venture bits of moving fluff courage of our questions white dwarf billions upon billions intelligent beings. Stirred by starlight, two ghostly white figures in coveralls and helmets are soflty dancing quasar billions upon billions, great turbulent clouds, a mote of dust suspended in a sunbeam circumnavigated extraplanetary culture, Euclid citizens of distant epochs, worldlets a mote of dust suspended in a sunbeam quasar cosmic fugue star stuff harvesting star light hearts of the stars, billions upon billions.\n" +
                    "Tesseract the carbon in our apple pies brain is the seed of intelligence galaxies preserve and cherish that pale blue dot, concept of the number one with pretty stories for which there's little good evidence encyclopaedia galactica Sea of Tranquility? Great turbulent clouds hearts of the stars radio telescope. Inconspicuous motes of rock and gas, science, realm of the galaxies. Science, kindling the energy hidden in matter paroxysm of global death tesseract how far away! Inconspicuous motes of rock and gas concept of the number one descended from astronomers, Apollonius of Perga, billions upon billions Euclid.\n" +
                    "Rings of Uranus Euclid, concept of the number one great turbulent clouds billions upon billions, a still more glorious dawn awaits realm of the galaxies, not a sunrise but a galaxyrise Tunguska event citizens of distant epochs explorations inconspicuous motes of rock and gas shores of the cosmic ocean rings of Uranus from which we spring culture! Tingling of the spine. The carbon in our apple pies cosmic fugue astonishment of brilliant syntheses not a sunrise but a galaxyrise tesseract inconspicuous motes of rock and gas gathered by gravity laws of physics rings of Uranus dispassionate extraterrestrial observer a very small stage in a vast cosmic arena.\n" +
                    "Sea of Tranquility billions upon billions with pretty stories for which there's little good evidence vastness is bearable only through love. Billions upon billions! Gathered by gravity tesseract, permanence of the stars rich in heavy atoms hearts of the stars with pretty stories for which there's little good evidence rich in mystery! Intelligent beings star stuff harvesting star light extraplanetary. Made in the interiors of collapsing stars Apollonius of Perga, cosmos, cosmic fugue tingling of the spine Cambrian explosion! Rogue, Sea of Tranquility! Not a sunrise but a galaxyrise inconspicuous motes of rock and gas rich in mystery a mote of dust suspended in a sunbeam a still more glorious dawn awaits, made in the interiors of collapsing stars prime number, radio telescope, ship of the imagination, how far away!\n" +
                    "Galaxies descended from astronomers. Hypatia at the edge of forever hundreds of thousands galaxies, rich in heavy atoms encyclopaedia galactica Apollonius of Perga, courage of our questions quasar hydrogen atoms birth, brain is the seed of intelligence a billion trillion. Inconspicuous motes of rock and gas prime number. Billions upon billions, Tunguska event another world billions upon billions corpus callosum cosmic fugue. From which we spring a billion trillion explorations take root and flourish! Trillion network of wormholes?\n" +
                    "Explorations trillion, at the edge of forever Rig Veda dispassionate extraterrestrial observer, hydrogen atoms! Across the centuries hundreds of thousands Rig Veda? Venture Sea of Tranquility rich in heavy atoms finite but unbounded billions upon billions, Rig Veda. Star stuff harvesting star light extraplanetary astonishment, cosmic fugue? Vastness is bearable only through love, gathered by gravity. Made in the interiors of collapsing stars. Billions upon billions are creatures of the cosmos, billions upon billions kindling the energy hidden in matter courage of our questions trillion kindling the energy hidden in matter?\n" +
                    "Hearts of the stars kindling the energy hidden in matter concept of the number one. Not a sunrise but a galaxyrise of brilliant syntheses! Prime number. Across the centuries dream of the mind's eye Jean-Francois Champollion vanquish the impossible. Take root and flourish extraordinary claims require extraordinary evidence venture prime number dispassionate extraterrestrial observer cosmic fugue inconspicuous motes of rock and gas white dwarf! Descended from astronomers consciousness. Tingling of the spine billions upon billions bits of moving fluff? A billion trillion Flatland.\n" +
                    "At the edge of forever great turbulent clouds something incredible is waiting to be known venture. Muse about. Great turbulent clouds rich in heavy atoms the sky calls to us Jean-Francois Champollion Drake Equation, vanquish the impossible, explorations, Rig Veda a still more glorious dawn awaits Drake Equation, circumnavigated hydrogen atoms hearts of the stars a billion trillion great turbulent clouds Apollonius of Perga, vanquish the impossible, extraordinary claims require extraordinary evidence of brilliant syntheses the only home we've ever known at the edge of forever. Hearts of the stars, Hypatia globular star cluster.\n" +
                    "Extraplanetary preserve and cherish that pale blue dot two ghostly white figures in coveralls and helmets are soflty dancing billions upon billions dispassionate extraterrestrial observer white dwarf emerged into consciousness made in the interiors of collapsing stars, white dwarf network of wormholes Jean-Francois Champollion white dwarf, preserve and cherish that pale blue dot Sea of Tranquility a mote of dust suspended in a sunbeam venture? Star stuff harvesting star light at the edge of forever take root and flourish, tendrils of gossamer clouds? Vastness is bearable only through love not a sunrise but a galaxyrise? From which we spring, at the edge of forever radio telescope something incredible is waiting to be known Apollonius of Perga Orion's sword the only home we've ever known paroxysm of global death a mote of dust suspended in a sunbeam billions upon billions.\n" +
                    "Prime number emerged into consciousness brain is the seed of intelligence a mote of dust suspended in a sunbeam astonishment. Decipherment Vangelis Hypatia consciousness ship of the imagination. A very small stage in a vast cosmic arena Drake Equation shores of the cosmic ocean network of wormholes? The only home we've ever known a billion trillion, colonies preserve and cherish that pale blue dot vanquish the impossible, a mote of dust suspended in a sunbeam laws of physics Rig Veda corpus callosum dream of the mind's eye, the ash of stellar alchemy white dwarf. Decipherment, explorations rings of Uranus and billions upon billions upon billions upon billions upon billions upon billions upon billions?").save()

            Content social = new Content(content: "Resist changemaker issue outcomes collaborative cities state of play. Or the resistance issue outcomes outcomes collaborate. Effective circular; thought partnership; program area, effective philanthropy families changemaker shine. Innovation youth low-hanging fruit, grit design thinking humanitarian vibrant. Synergy academic storytelling changemaker theory of change. Empower emerging agile storytelling to. Save the world black lives matter catalyze shine NGO empower communities inspire movements. Compassion; inclusive deep dive then agile challenges and opportunities co-create commitment. Compelling; impact, social capital radical living a fully ethical life transparent. Cultivate catalyze, entrepreneur and empathetic inspirational, compelling outcomes. Social capital but, commitment, compassion the inclusive. Catalyze, equal opportunity; impact social return on investment greenwashing scale and impact triple bottom line. Citizen-centered, parse empower thought provoking unprecedented challenge. A movements commitment NGO policymaker human-centered disrupt. Grit activate uplift move the needle social capital. Shine social intrapreneurship natural resources innovate, strategize overcome injustice overcome injustice effective altruism. Families but,.").save()

            Categorie ctg = new Categorie(name: "La famille des Lorems").save()
            Categorie ctg2 = new Categorie(name: "World War 2").save()
            Categorie ctg3 = new Categorie(name: "Psychologie").save()

            Article article1 = new Article(title: "Lorem Ipsum", content: lorem, categorie: ctg).save()
            Article article2 = new Article(title: "Bacon Ipsum", content: bacon, categorie: ctg).save()
            Article article3 = new Article(title: "Cat Ipsum", content: cat, categorie: ctg).save()
            Article article4 = new Article(title: "Seconde Guerre Mondiale", content: ww2, categorie: ctg2).save()
            Article article5 = new Article(title: "Cupcake Ipsum", content: cup, categorie: ctg).save()
            Article article6 = new Article(title: "Bob Ross Ipsum", content: bob, categorie: ctg).save()
            Article article7 = new Article(title: "Hairy Ipsum", content: hairy, categorie: ctg).save()
            Article article8 = new Article(title: "Hodor Ipsum", content: hodor, categorie: ctg).save()
            Article article9 = new Article(title: "Pirate Ipsum", content: pirate, categorie: ctg).save()
            Article article10 = new Article(title: "Pommy Ipsum", content: pommy, categorie: ctg).save()
            Article article11 = new Article(title: "Cosmos Ipsum", content: cosmos, categorie: ctg).save()

            User user1 = new User(username: "Luigi", password: "123123").save(flush: true)
        }
    }
    def destroy = {
    }
}
